spring.data.mongodb.uri=mongodb+srv://marcusdimitri7_db_user:UxwyIBsx1lxXJtBa@javamongocluster.1ewn9wg.mongodb.net/Java_MongoDB?retryWrites=true&w=majority&appName=JavaMongoCluster
spring.data.mongodb.database=Java_MongoDB
spring.data.mongodb.auto-index-creation=true
viacep.base-url=https://viacep.com.br/ws
server.port=8080
server.error.include-stacktrace=never
